### ISSUE TITLE
com.kynetics.uf.service E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by dp25121963** [eclipse/hara-ddiclient#21]
Hi,
Using the Update Factory client service I started receiving the the following errors when connecting to the sand box at: https://hawkbit.eclipseprojects.io/

2022-12-07 12:38:36.668 3465-3997/com.kynetics.uf.service E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.kynetics.uf.service, PID: 3465
    java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
        at okhttp3.internal.connection.RealCall.enterNetworkInterceptorExchange(RealCall.kt:237)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:55)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.eclipse.hara.ddi.security.HawkbitAuthenticationRequestInterceptor.intercept(HawkbitAuthenticationRequestInterceptor.kt:54)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:533)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

I have little understanding of the entire system so I'm reluctant to commit a fix but the following modification resolved the issue for me:

class HawkbitAuthenticationRequestInterceptor(authentications: Set<Authentication>) : Interceptor {

    private val authentications: List<Authentication>
    private var authenticationUse = 0

    init {
        Objects.requireNonNull(authentications)
        this.authentications = ArrayList(authentications)
    }

    @Throws(IOException::class)
    override fun intercept(chain: Interceptor.Chain): Response {
        if (authentications.isEmpty()) {
            return chain.proceed(chain.request())
        }

        val originalRequest = chain.request()
        val builder = originalRequest.newBuilder()
        val size = authentications.size
        val exitValue = authenticationUse
        var response: Response
        var LastResponse : Response? = null
        do {
            val authentication = authentications[authenticationUse]
            builder.header(authentication.header, authentication.headerValue)
            LastResponse?.closeQuietly()
            response = chain.proceed(builder.build())
            LastResponse = response
            if (response.code != 401) {
                break
            }
            authenticationUse = ++authenticationUse % size
        } while (authenticationUse != exitValue)

        return response
    }
}

I hope this makes sense and is the correct approach to resolving the issue if anyone else comes across the same error.

Daniel

**Comment by diegorondini** [comment]
Thanks for reporting, we'll have a look.
